FROM node:22

RUN npm install standard -g
RUN npm install express -g
RUN npm install nodemon -g
RUN mkdir -p /home/node-app

WORKDIR /home/node-app

EXPOSE 3000

CMD [ "nodemon", "--legacy-watch", "app.js" ]