### Get all snippets or quered
GET http://localhost:3000/snippets?id=cec7edfb-3244-11f0-9eba-0242ac120002


### Create a new snippet
POST http://localhost:3000/snippets
Content-Type: application/json

{
  "user_id": "1f073959-f9be-11ef-b248-0242ac130002",
  "title": "jsjvwv",
  "description": "ccwcwc",
  "lang": "astralopiteco",
  "code": "abracasumabra"
}

### Put a snippet
PUT http://localhost:3000/snippets/5f63998e-fdff-11ef-af9c-0242ac130002
Content-Type: application/json

{
  "user_id": "5f5d399a-fdff-11ef-af9c-0242ac130002",
  "title": "Hola Mundo en Tu puta madre",
  "description": "Un simple hola mundo en Python",
  "lang": "Python",
  "code": "print(\"Hola, mundo!\")"
}

### Delete a snippet
DELETE http://localhost:3000/snippets/5f63998e-fdff-11ef-af9c-0242ac130002

### Update a snippet
PATCH http://localhost:3000/snippets/cec7f030-3244-11f0-9eba-0242ac120002
Content-Type: application/json

{
  "lang44": "JavaScript"
}