### Get all snippets or quered
GET http://localhost:3000/snippets?title=Python&&description=a
### Get a single snippet by id
GET http://localhost:3000/snippets/8a41c75a-f8ac-11ef-a64c-0242ac120002

### Create a new snippet
POST http://localhost:3000/snippets
Content-Type: application/json

{
  "user_id": "1f073959-f9be-11ef-b248-0242ac130002",
  "title": "Suma",
  "description": "no obli",
  "lang": "astralopiteco",
  "code": "abracasumabra"
}

### Put a snippet
PUT 
Content-Type: application/json

{
  "id": "0297f8cb-f166-4494-9a26-0379ae046dfa",
  "title": "Hello World in Python",
  "code": "print('Hello, World!')",
  "language": "Python",
  "description": "A simple script to print 'Hello, World!'"
}