### Get all snippets or quered
GET http://localhost:3000/snippets
### Get a single snippet by id
GET http://localhost:3000/snippets/8a41c75a-f8ac-11ef-a64c-0242ac120002

### Create a new snippet
POST http://localhost:3000/snippets
Content-Type: application/json

{
  "user_id": "1f073959-f9be-11ef-b248-0242ac130002",
  "title": "",
  "description": "",
  "lang": "astralopiteco",
  "code": "abracasumabra"
}

### Put a snippet
PUT http://localhost:3000/snippets/5f63998e-fdff-11ef-af9c-0242ac130002
Content-Type: application/json

{
  "user_id": "5f5d399a-fdff-11ef-af9c-0242ac130002",
  "title": "Hola Mundo en Tu puta madre",
  "description": "Un simple hola mundo en Python",
  "lang": "Python",
  "code": "print(\"Hola, mundo!\")"
}